services:
  db:
    container_name: db-container
    image: postgres:alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck: # Add healthcheck to ensure PostgreSQL is ready
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  app:
    container_name: aspnet-core-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword
    depends_on:
      - db
    volumes:
      - ./data-protection:/root/.aspnet/DataProtection-Keys

volumes:
  postgres-data:
  data-protection:
